[book]
authors = ["JoaoCostaIFG"]
language = "en"
multilingual = false
src = "src"
title = "Paul's Wiki"

[output.html]
additional-css = [
  "./theme/catppuccin.css",
  "./theme/catppuccin-admonish.css",
  "./theme/catppuccin-alerts.css",
]
default-theme = "latte"
preferred-dark-theme = "mocha"
no-section-label = true
git-repository-url = "https://github.com/mooneydude/wiki"
git-repository-icon = "fa-github"
# cname = "wiki.joaocosta.dev"
